In [2]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path("/content/")

DATA_PROCESSED = BASE_DIR / "datos" / "procesados"
DATA_GEO = BASE_DIR / "datos" / "geo"

DATA_GEO.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

print("carpeta geo:", DATA_GEO)

carpeta geo: /content/datos/geo

In [3]:
#Cargamos dataset limpio
ruta_limpio = DATA_PROCESSED / "dataset_limpio.csv"

df = pd.read_csv(ruta_limpio)
print("Registros:", len(df))
print("Columnas:")
print(df.columns.tolist())

df.head()

Registros: 20144
Columnas:
['company_id', 'product_area', 'event_date', 'ticket_count', 'deployment_count', 'failed_deployments', 'avg_lead_time_hours', 'rollback_count', 'incident_count', 'avg_resolution_time_hours', 'total_downtime_min', 'avg_cpu_usage_pct', 'avg_memory_usage_pct', 'avg_response_time_ms', 'avg_error_rate_pct', 'avg_availability_pct', 'avg_requests_per_minute', 'deployment_failure_rate_pct', 'rollback_rate_pct', 'anio', 'mes', 'dia', 'dia_semana', 'es_fin_semana', 'sin_datos_monitoreo']

,company_id,product_area,event_date,ticket_count,deployment_count,failed_deployments,avg_lead_time_hours,rollback_count,incident_count,avg_resolution_time_hours,...,avg_availability_pct,avg_requests_per_minute,deployment_failure_rate_pct,rollback_rate_pct,anio,mes,dia,dia_semana,es_fin_semana,sin_datos_monitoreo
0,100001,Analytics,2026-01-01,3,0,0,NaN,0,0,NaN,...,98.422,7051.0,NaN,NaN,2026,1,1,Thursday,False,False
1,100001,Analytics,2026-01-02,1,0,0,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,2026,1,2,Friday,False,True
2,100001,Analytics,2026-01-03,2,1,0,18.29,0,0,NaN,...,96.012,4186.0,0.0,0.0,2026,1,3,Saturday,True,False
3,100001,Analytics,2026-01-04,1,0,0,NaN,0,0,NaN,...,95.885,854.0,NaN,NaN,2026,1,4,Sunday,True,False
4,100001,Analytics,2026-01-05,1,0,0,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,2026,1,5,Monday,False,True

In [4]:
#verificamos el id de todas las empresas
empresas = sorted(df["company_id"].unique())
print("Cantidad de empresas:", len(empresas))
print("Empresas:")
print(empresas)

Cantidad de empresas: 25
Empresas:
[np.int64(100001), np.int64(100002), np.int64(100003), np.int64(100004), np.int64(100005), np.int64(100006), np.int64(100007), np.int64(100008), np.int64(100009), np.int64(100010), np.int64(100011), np.int64(100012), np.int64(100013), np.int64(100014), np.int64(100015), np.int64(100016), np.int64(100017), np.int64(100018), np.int64(100019), np.int64(100020), np.int64(100021), np.int64(100022), np.int64(100023), np.int64(100024), np.int64(100025)]

In [7]:
#Ubicaciones con latitud y longitud
ubicaciones = {
    100001: ("San Salvador", "San Salvador", 13.6929, -89.2182),
    100002: ("La Libertad", "Santa Tecla", 13.6769, -89.2797),
    100003: ("Santa Ana", "Santa Ana", 13.9942, -89.5597),
    100004: ("San Miguel", "San Miguel", 13.4833, -88.1833),
    100005: ("La Paz", "Zacatecoluca", 13.5086, -88.8686),
    100006: ("Ahuachapán", "Ahuachapán", 13.9214, -89.8450),
    100007: ("Sonsonate", "Sonsonate", 13.7189, -89.7242),
    100008: ("Chalatenango", "Chalatenango", 14.0381, -88.9322),
    100009: ("Cuscatlán", "Cojutepeque", 13.7228, -88.9353),
    100010: ("Cabañas", "Sensuntepeque", 13.8761, -88.6331),
    100011: ("San Vicente", "San Vicente", 13.6442, -88.7778),
    100012: ("Usulután", "Usulután", 13.3444, -88.4392),
    100013: ("Morazán", "San Francisco Gotera", 13.6928, -88.1025),
    100014: ("La Unión", "La Unión", 13.3369, -87.8439),
    100015: ("San Salvador", "Soyapango", 13.7139, -89.1397),
    100016: ("San Salvador", "Mejicanos", 13.7314, -89.1914),
    100017: ("San Salvador", "Apopa", 13.8058, -89.1783),
    100018: ("La Libertad", "Antiguo Cuscatlán", 13.6733, -89.2536),
    100019: ("La Libertad", "Colón (Lourdes)", 13.7258, -89.3667),
    100020: ("Santa Ana", "Metapán", 14.3311, -89.4447),
    100021: ("Santa Ana", "Chalchuapa", 13.9856, -89.6806),
    100022: ("Sonsonate", "Izalco", 13.7431, -89.6731),
    100023: ("Usulután", "Jiquilisco", 13.3150, -88.5839),
    100024: ("San Miguel", "Ciudad Barrios", 13.7631, -88.2614),
    100025: ("La Libertad", "Puerto de La Libertad", 13.4883, -89.3200)
}

In [9]:
#df geografico
registros_geo = []

for company_id, datos in ubicaciones.items():

    departamento, municipio, latitud, longitud = datos

    registros_geo.append({
        "company_id": company_id,
        "departamento": departamento,
        "municipio": municipio,
        "latitud": latitud,
        "longitud": longitud,
        "tipo_ubicacion": "Sintetica"
    })

df_geo = pd.DataFrame(registros_geo)

df_geo.head()

   company_id  departamento     municipio  latitud  longitud tipo_ubicacion
0      100001  San Salvador  San Salvador  13.6929  -89.2182      Sintetica
1      100002   La Libertad   Santa Tecla  13.6769  -89.2797      Sintetica
2      100003     Santa Ana     Santa Ana  13.9942  -89.5597      Sintetica
3      100004    San Miguel    San Miguel  13.4833  -88.1833      Sintetica
4      100005        La Paz  Zacatecoluca  13.5086  -88.8686      Sintetica

In [12]:
#validacion de las empresas
print("Empresas en dataset:", df["company_id"].nunique())
print("Empresas en dimension geografica:", df_geo["company_id"].nunique())
faltantes_geo = set(df["company_id"]) - set(df_geo["company_id"])

print("Empresas sin ubicación:", faltantes_geo)

Empresas en dataset: 25
Empresas en dimension geografica: 25
Empresas sin ubicación: set()

In [14]:
#validacion de coordenadas
df_geo["latitud"] = pd.to_numeric(
    df_geo["latitud"],
    errors="coerce"
)

df_geo["longitud"] = pd.to_numeric(
    df_geo["longitud"],
    errors="coerce"
)
mask_valida = (
    df_geo["latitud"].between(13, 15) &
    df_geo["longitud"].between(-91, -87)
)

print("Total de empresas:", len(df_geo))
print("Coordenadas válidas:", mask_valida.sum())
print("Coordenadas a revisar:", (~mask_valida).sum())

Total de empresas: 25
Coordenadas válidas: 25
Coordenadas a revisar: 0

In [17]:
#guardamos la dimension geografica
ruta_geo = DATA_GEO / "empresas_geografia_sintetica.csv"

df_geo.to_csv(
    ruta_geo,
    index=False,
    encoding="utf-8"
)

print("Archivo guardado en:")
print(ruta_geo)

Archivo guardado en:
/content/datos/geo/empresas_geografia_sintetica.csv

In [18]:
#Unimos los datos por medio de la llave company_id
df_devops_geo = df.merge(
    df_geo,
    on="company_id",
    how="left"
)
print(df_devops_geo.shape)

df_devops_geo.head()

(20144, 30)

,company_id,product_area,event_date,ticket_count,deployment_count,failed_deployments,avg_lead_time_hours,rollback_count,incident_count,avg_resolution_time_hours,...,mes,dia,dia_semana,es_fin_semana,sin_datos_monitoreo,departamento,municipio,latitud,longitud,tipo_ubicacion
0,100001,Analytics,2026-01-01,3,0,0,NaN,0,0,NaN,...,1,1,Thursday,False,False,San Salvador,San Salvador,13.6929,-89.2182,Sintetica
1,100001,Analytics,2026-01-02,1,0,0,NaN,0,0,NaN,...,1,2,Friday,False,True,San Salvador,San Salvador,13.6929,-89.2182,Sintetica
2,100001,Analytics,2026-01-03,2,1,0,18.29,0,0,NaN,...,1,3,Saturday,True,False,San Salvador,San Salvador,13.6929,-89.2182,Sintetica
3,100001,Analytics,2026-01-04,1,0,0,NaN,0,0,NaN,...,1,4,Sunday,True,False,San Salvador,San Salvador,13.6929,-89.2182,Sintetica
4,100001,Analytics,2026-01-05,1,0,0,NaN,0,0,NaN,...,1,5,Monday,False,True,San Salvador,San Salvador,13.6929,-89.2182,Sintetica

In [19]:
#verificamos que no perdimos datos
print("Registros originales:", len(df))
print("Registros geográficos:", len(df_devops_geo))

Registros originales: 20144
Registros geográficos: 20144

In [20]:
#guardamos el dataset listo para ArcGis
ruta_arcgis = DATA_GEO / "dataset_devops_geografico.csv"

df_devops_geo.to_csv(
    ruta_arcgis,
    index=False,
    encoding="utf-8"
)

print("Dataset para ArcGIS:")
print(ruta_arcgis)

Dataset para ArcGIS:
/content/datos/geo/dataset_devops_geografico.csv